distinguishedName = [ relativeDistinguishedName
          *( COMMA relativeDistinguishedName ) ]
relativeDistinguishedName = attributeTypeAndValue
          *( PLUS attributeTypeAndValue )
attributeTypeAndValue = attributeType EQUALS attributeValue
attributeType = descr / numericoid
attributeValue = string / hexstring

; The following characters are to be escaped when they appear
; in the value to be encoded: ESC, one of <escaped>, leading
; SHARP or SPACE, trailing SPACE, and NULL.
string =   [ ( leadchar / pair ) [ stringnonlead ] ]
		 ; regex = ([^ &quot;#+,;&lt;>\\]|\\[\\"\+,;<> #=\dA-Fa-f])(([^&quot;+,;&lt;>\\]|\\[\\"\+,;<> #=\dA-Fa-f])*[^ &quot;+,;&lt;>\\]|\\[\\"\+,;<> #=\dA-Fa-f])?
;		 leadchar = [^ &quot;#+,;&lt;>\\]|\\[\\"\+,;<> #=\dA-Fa-f]
;trailchar = [^ &quot;+,;&lt;>\\]|\\[\\"\+,;<> #=\dA-Fa-f]
; stringchar = [^&quot;+,;&lt;>\\]|\\[\\"\+,;<> #=\dA-Fa-f]


		 
stringnonlead = *( stringchar / pair ) ( trailchar / pair )


leadchar = %x21 / %x24-2A / %x2D-3A / %x3D / %x3F-5B / %x5D-10ffff

trailchar  =  %x21 / %x23-2A / %x2D-3A / %x3D / %x3F-5B / %x5D-10ffff

stringchar = %x20-21 / %x23-2A / %x2D-3A / %x3D / %x3F-5B / %x5D-10ffff

pair = ESC ( ESC / special / hexpair )
special = escaped / SPACE / SHARP / EQUALS
escaped = DQUOTE / PLUS / COMMA / SEMI / LANGLE / RANGLE
hexstring = SHARP 1*hexpair
hexpair = HEX HEX
