selection = reference [expression]
expression = "[" (elem-expr / attr-expr)
                      1*[oper (elem-expr / attr-expr)] "]"
elem-expr = (elem-path / "." / "..") compar value
elem-path = (element / "*") 1*["/" / "*" / element] ["*" / element]
attr-expr = [elem-path "/"] attribute compar value

reference = elem-reference / attr-reference
elem-reference =  "/" 1*("/" / "/*" / ("/" element))
attr-reference = reference attribute

oper = "and" / "or"
compar = "=" / "<" / ">"
element = [ns] string
attribute = "@" [ns] string
ns = string ":"
string = 1*ALPHA
  ; <any sequence of data supported by XML in names of XML
  ;  element, and/or attribute or prefixes of namespaces>
value = 1*DIGIT / ( DQUOTE 1*(ALPHA / DIGIT) DQUOTE)
  ; <any sequence of data supported by XML as a value of the
  ;  XML element and/or attribute>
