; This ABNF is psychotic.  It is intended to represent the 8-bit values used in unicode.
; As such, an NAI has no direct way to be represented in unicode due to the \x construct.

nai         =  username
nai         =/ [ username ] "@" realm

username    =  dot-string
dot-string  =  string *( "." string)
string      =  *nai-char
nai-char    =  %x7e
nai-char    =/ "\" 2HEXDIG

realm       =  1*( label "." ) label
label       =  let-dig *(ldh-str)
ldh-str     =  *( alpha / digit / "-" ) let-dig
let-dig     =  alpha / digit
alpha       =  %x41-5A  ; 'A'-'Z'
alpha       =/ %x61-7A  ; 'a'-'z'
digit       =  %x30-39  ; '0'-'9'
